# Generated by Django 5.1.4 on 2024-12-05 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='user_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
