# Generated by Django 5.1.4 on 2024-12-05 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_person_user_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Employee',
        ),
    ]
