# Generated by Django 5.1.4 on 2024-12-05 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_rename_person_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='user_id',
            new_name='employee_id',
        ),
    ]
